### ISSUE TITLE
tabbing

### ISSUE THREAD

**Issue by mikebutts** [montresor34/colmar_academy#4]
This is NOT a big deal, just something I thought was notable

![image](https://user-images.githubusercontent.com/8017734/34561721-65232dce-f119-11e7-8d7f-94a44376cc93.png)

your tabs are rather large, typically you would use 2 or 4 spaces.

example from another project:
![image](https://user-images.githubusercontent.com/8017734/34561749-821f903e-f119-11e7-8cc9-616da074ffca.png)

  The reason I point it out, is on big projects with alot of nesting you will have to start horizontal scrolling.

**Comment by jeneiss** [comment]
Fixed.
